POST http://localhost:5000/api/Admin/create_product
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAxLCJpYXQiOjE3ODk4NjE0MTksImV4cCI6MTgzMTMzMzQxOX0.aXgd99QdJXVkJinAq5G_borpHX0ZV68NxZGgyZvXpaI
------WebKitFormBoundary
Content-Disposition: form-data; name="category_id"

3
------WebKitFormBoundary
Content-Disposition: form-data; name="title"

REDMI 10 Power
------WebKitFormBoundary
Content-Disposition: form-data; name="description"

Redmi smartphone with 128GB storage
------WebKitFormBoundary
Content-Disposition: form-data; name="old_price"

13500
------WebKitFormBoundary
Content-Disposition: form-data; name="stock"

100
------WebKitFormBoundary
Content-Disposition: form-data; name="product_image"; filename="redmi.jpg"
Content-Type: image/jpeg

< ./redmi.jpg
------WebKitFormBoundary--